name: Trigger veramo-website build
on:
  repository_dispatch:
    types: [on-demand-build-website]
  workflow_dispatch:
  push:
    branches:
      - 'italo/fix-docs'
jobs:
  docusaurus:
    name: Docusaurus build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Setup docusaurus cache
        uses: actions/cache@v3
        with:
          path: build
          key: docusaurus.${{ github.sha }}
      - run: yarn install --frozen-lockfile
      - run: yarn prettier --check
      - run: yarn build
  open-api:
    name: OpenAPI build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Setup open-api cache
        uses: actions/cache@v3
        with:
          path: docs/api
          key: openapi.${{ github.sha }}
      - run: yarn install --frozen-lockfile
      - run: yarn build:veramo
  merge:
    name: Merge and push
    needs:
      - docusaurus
      - open-api
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Recover docusaurus output
        uses: actions/cache@v3
        with:
          path: build
          key: docusaurus.${{ github.sha }}
      - name: Recover open-api output
        uses: actions/cache@v3
        with:
          path: docs/api
          key: openapi.${{ github.sha }}
      - name: Config Git
        run: |
          git config --local user.name '[bot] veramo-website'
          git config --local user.email 'veramo-website@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Commit changes and tag
        run: |
          git clone https://github.com/uport-project/veramo.git veramo
          RELEASE_VERSION=`echo "console.log(require('./veramo/lerna.json').version)" | node`
          git status
          echo Deploying docs for version v$RELEASE_VERSION
          git add .
          git commit -m "chore(release): :rocket: api docs v${RELEASE_VERSION}"
          git tag -a v$RELEASE_VERSION -m "v${RELEASE_VERSION}"
      - name: Push to repo
        run: |
          git push origin $GITHUB_REF --tags
